
server:
#  address: ${SERVICE_ADDRESS:0.0.0.0}
  port: 8021 # Use random open port, run with --port=8080 to override
  servlet:
    context-path: /mps

spring:

  jpa:
    hibernate:
      ddl-auto: none
#      naming:
#        physical-strategy: application.framework.UppercaseNamingStrategy
    properties:
      hibernate:
        #Needed for POSTGRES
#        globally_quoted_identifiers: true
        auto_quote_keyword: true
        format_sql: true
        use_sql_comments: true
    show-sql: true

  liquibase:
    enabled: false
#    enabled: true
    change-log: classpath:db/changelog/changelog.xml

logging:
    level:
      liquibase: INFO
      org:
        hibernate:
          type:
            descriptor:
              sql:
                BasicBinder: TRACE
      jdbc:
        sqlonly: OFF
        sqltiming: OFF
        audit: OFF
        resultset: OFF
        resultsettable: OFF
        connection: OFF
log4jdbc:
  dump:
    sql:
      addsemicolon: false


---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce2
    username: msalima
    password: abcd1234!@#$
    initialization-mode: never
    platform: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    contexts: test
  h2:
    console:
      enabled: false

---
spring:
  config:
    activate:
      on-profile: development
  datasource:
    url: jdbc:h2:mem:testdb;mode=ORACLE;DB_CLOSE_ON_EXIT=FALSE #;TRACE_LEVEL_FIle=4
    username: sa
    password:
    platform: h2
    driver-class-name: org.h2.Driver
#    initialization-mode: embedded
    initialization-mode: never
  liquibase:
    contexts: development
    enabled: true
  h2:
    console:
      enabled: true

#TODO add more logging
logging:
  level:
    jdbc:
      sqltiming: DEBUG
      resultsettable: INFO

log4jdbc:
  dump:
    sql:
      addsemicolon: true
