log4jdbc:
  dump:
    sql:
      addsemicolon: true

spring:
  liquibase:
    enabled: true
    contexts: development
    drop-first: false
    change-log: classpath:db/changelog/changelog.xml
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      platform: h2
  h2:
    console:
      enabled: true
      path: /admin/dbconsole
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true # formats SQL to multiline output
        use_sql_comments: true # ORM inserted explanation of the intent of the SQL


logging:
  level:
    org:
      hibernate:
        cache: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        engine:
          transaction:
            internal:
              TransactionImpl: DEBUG
          jdbc:
            env:
              internal:
                JdbcEnvironmentInitiator: DEBUG
        cfg:
          Settings: DEBUG
        jpa:
          internal:
            util:
      springframework:
        transaction: TRACE
        orm:
          jpa: DEBUG
    jdbc:
      sqlonly: OFF
      sqltiming: DEBUG
      audit: OFF
      resultset: OFF
      resultsettable: INFO
      connection: OFF

---
spring:
  config:
    activate:
      on-profile: integrationTest
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false
  liquibase:
    enabled: false
  sql:
    init:
      platform: h2
      mode: never


